-- Add test_value_2 through test_value_20 to testing.redis_basic_test (same type as test_value_1).

ALTER TABLE testing.redis_basic_test
  ADD COLUMN IF NOT EXISTS test_value_2 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_3 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_4 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_5 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_6 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_7 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_8 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_9 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_10 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_11 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_12 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_13 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_14 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_15 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_16 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_17 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_18 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_19 NUMERIC,
  ADD COLUMN IF NOT EXISTS test_value_20 NUMERIC;
