-- Per-tenant performance rollup tables (wide numeric columns) + NOTIFY triggers.
-- Tables: users_<slot>.performance_total_<slot> (one row, user_id = 1) and users_<slot>.performance_monitors_<slot> (per monitor).
-- Stream: performance_rollups (see backend/core/stream_registry.py).

DO $$
DECLARE
  r RECORD;
  slot text;
  tot text;
  mon text;
  ddl text;
BEGIN
  FOR r IN
    SELECT c.table_schema AS sch, c.table_name AS tname
    FROM information_schema.tables c
    WHERE c.table_type = 'BASE TABLE'
      AND c.table_schema ~ '^users_[0-9]{4}$'
      AND c.table_name ~ '^trades_[0-9]{4}$'
      AND substring(c.table_schema from '([0-9]{4})$') = substring(c.table_name from 'trades_([0-9]{4})$')
  LOOP
    slot := substring(r.sch from '([0-9]{4})$');
    tot := 'performance_total_' || slot;
    mon := 'performance_monitors_' || slot;
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.tables x
      WHERE x.table_schema = r.sch AND x.table_name = tot
    ) THEN
      ddl := format($ct$
        CREATE TABLE %I.%I (
            user_id INTEGER PRIMARY KEY DEFAULT 1 CHECK (user_id = 1),
            1d_td_pnl_live NUMERIC(24,8),
            1d_td_ret_pct_live NUMERIC(14,6),
            1d_td_fees_live NUMERIC(24,8),
            1d_td_trades_n_live INTEGER,
            1d_td_win_rate_live NUMERIC(14,6),
            1d_td_pnl_paper NUMERIC(24,8),
            1d_td_ret_pct_paper NUMERIC(14,6),
            1d_td_fees_paper NUMERIC(24,8),
            1d_td_trades_n_paper INTEGER,
            1d_td_win_rate_paper NUMERIC(14,6),
            1d_td_pnl_test NUMERIC(24,8),
            1d_td_ret_pct_test NUMERIC(14,6),
            1d_td_fees_test NUMERIC(24,8),
            1d_td_trades_n_test INTEGER,
            1d_td_win_rate_test NUMERIC(14,6),
            1d_prev_pnl_live NUMERIC(24,8),
            1d_prev_ret_pct_live NUMERIC(14,6),
            1d_prev_fees_live NUMERIC(24,8),
            1d_prev_trades_n_live INTEGER,
            1d_prev_win_rate_live NUMERIC(14,6),
            1d_prev_pnl_paper NUMERIC(24,8),
            1d_prev_ret_pct_paper NUMERIC(14,6),
            1d_prev_fees_paper NUMERIC(24,8),
            1d_prev_trades_n_paper INTEGER,
            1d_prev_win_rate_paper NUMERIC(14,6),
            1d_prev_pnl_test NUMERIC(24,8),
            1d_prev_ret_pct_test NUMERIC(14,6),
            1d_prev_fees_test NUMERIC(24,8),
            1d_prev_trades_n_test INTEGER,
            1d_prev_win_rate_test NUMERIC(14,6),
            1w_td_pnl_live NUMERIC(24,8),
            1w_td_ret_pct_live NUMERIC(14,6),
            1w_td_fees_live NUMERIC(24,8),
            1w_td_trades_n_live INTEGER,
            1w_td_win_rate_live NUMERIC(14,6),
            1w_td_pnl_paper NUMERIC(24,8),
            1w_td_ret_pct_paper NUMERIC(14,6),
            1w_td_fees_paper NUMERIC(24,8),
            1w_td_trades_n_paper INTEGER,
            1w_td_win_rate_paper NUMERIC(14,6),
            1w_td_pnl_test NUMERIC(24,8),
            1w_td_ret_pct_test NUMERIC(14,6),
            1w_td_fees_test NUMERIC(24,8),
            1w_td_trades_n_test INTEGER,
            1w_td_win_rate_test NUMERIC(14,6),
            1w_prev_pnl_live NUMERIC(24,8),
            1w_prev_ret_pct_live NUMERIC(14,6),
            1w_prev_fees_live NUMERIC(24,8),
            1w_prev_trades_n_live INTEGER,
            1w_prev_win_rate_live NUMERIC(14,6),
            1w_prev_pnl_paper NUMERIC(24,8),
            1w_prev_ret_pct_paper NUMERIC(14,6),
            1w_prev_fees_paper NUMERIC(24,8),
            1w_prev_trades_n_paper INTEGER,
            1w_prev_win_rate_paper NUMERIC(14,6),
            1w_prev_pnl_test NUMERIC(24,8),
            1w_prev_ret_pct_test NUMERIC(14,6),
            1w_prev_fees_test NUMERIC(24,8),
            1w_prev_trades_n_test INTEGER,
            1w_prev_win_rate_test NUMERIC(14,6),
            1m_td_pnl_live NUMERIC(24,8),
            1m_td_ret_pct_live NUMERIC(14,6),
            1m_td_fees_live NUMERIC(24,8),
            1m_td_trades_n_live INTEGER,
            1m_td_win_rate_live NUMERIC(14,6),
            1m_td_pnl_paper NUMERIC(24,8),
            1m_td_ret_pct_paper NUMERIC(14,6),
            1m_td_fees_paper NUMERIC(24,8),
            1m_td_trades_n_paper INTEGER,
            1m_td_win_rate_paper NUMERIC(14,6),
            1m_td_pnl_test NUMERIC(24,8),
            1m_td_ret_pct_test NUMERIC(14,6),
            1m_td_fees_test NUMERIC(24,8),
            1m_td_trades_n_test INTEGER,
            1m_td_win_rate_test NUMERIC(14,6),
            1m_prev_pnl_live NUMERIC(24,8),
            1m_prev_ret_pct_live NUMERIC(14,6),
            1m_prev_fees_live NUMERIC(24,8),
            1m_prev_trades_n_live INTEGER,
            1m_prev_win_rate_live NUMERIC(14,6),
            1m_prev_pnl_paper NUMERIC(24,8),
            1m_prev_ret_pct_paper NUMERIC(14,6),
            1m_prev_fees_paper NUMERIC(24,8),
            1m_prev_trades_n_paper INTEGER,
            1m_prev_win_rate_paper NUMERIC(14,6),
            1m_prev_pnl_test NUMERIC(24,8),
            1m_prev_ret_pct_test NUMERIC(14,6),
            1m_prev_fees_test NUMERIC(24,8),
            1m_prev_trades_n_test INTEGER,
            1m_prev_win_rate_test NUMERIC(14,6),
            1y_td_pnl_live NUMERIC(24,8),
            1y_td_ret_pct_live NUMERIC(14,6),
            1y_td_fees_live NUMERIC(24,8),
            1y_td_trades_n_live INTEGER,
            1y_td_win_rate_live NUMERIC(14,6),
            1y_td_pnl_paper NUMERIC(24,8),
            1y_td_ret_pct_paper NUMERIC(14,6),
            1y_td_fees_paper NUMERIC(24,8),
            1y_td_trades_n_paper INTEGER,
            1y_td_win_rate_paper NUMERIC(14,6),
            1y_td_pnl_test NUMERIC(24,8),
            1y_td_ret_pct_test NUMERIC(14,6),
            1y_td_fees_test NUMERIC(24,8),
            1y_td_trades_n_test INTEGER,
            1y_td_win_rate_test NUMERIC(14,6),
            1y_prev_pnl_live NUMERIC(24,8),
            1y_prev_ret_pct_live NUMERIC(14,6),
            1y_prev_fees_live NUMERIC(24,8),
            1y_prev_trades_n_live INTEGER,
            1y_prev_win_rate_live NUMERIC(14,6),
            1y_prev_pnl_paper NUMERIC(24,8),
            1y_prev_ret_pct_paper NUMERIC(14,6),
            1y_prev_fees_paper NUMERIC(24,8),
            1y_prev_trades_n_paper INTEGER,
            1y_prev_win_rate_paper NUMERIC(14,6),
            1y_prev_pnl_test NUMERIC(24,8),
            1y_prev_ret_pct_test NUMERIC(14,6),
            1y_prev_fees_test NUMERIC(24,8),
            1y_prev_trades_n_test INTEGER,
            1y_prev_win_rate_test NUMERIC(14,6),
            all_td_pnl_live NUMERIC(24,8),
            all_td_ret_pct_live NUMERIC(14,6),
            all_td_fees_live NUMERIC(24,8),
            all_td_trades_n_live INTEGER,
            all_td_win_rate_live NUMERIC(14,6),
            all_td_pnl_paper NUMERIC(24,8),
            all_td_ret_pct_paper NUMERIC(14,6),
            all_td_fees_paper NUMERIC(24,8),
            all_td_trades_n_paper INTEGER,
            all_td_win_rate_paper NUMERIC(14,6),
            all_td_pnl_test NUMERIC(24,8),
            all_td_ret_pct_test NUMERIC(14,6),
            all_td_fees_test NUMERIC(24,8),
            all_td_trades_n_test INTEGER,
            all_td_win_rate_test NUMERIC(14,6),
            all_prev_pnl_live NUMERIC(24,8),
            all_prev_ret_pct_live NUMERIC(14,6),
            all_prev_fees_live NUMERIC(24,8),
            all_prev_trades_n_live INTEGER,
            all_prev_win_rate_live NUMERIC(14,6),
            all_prev_pnl_paper NUMERIC(24,8),
            all_prev_ret_pct_paper NUMERIC(14,6),
            all_prev_fees_paper NUMERIC(24,8),
            all_prev_trades_n_paper INTEGER,
            all_prev_win_rate_paper NUMERIC(14,6),
            all_prev_pnl_test NUMERIC(24,8),
            all_prev_ret_pct_test NUMERIC(14,6),
            all_prev_fees_test NUMERIC(24,8),
            all_prev_trades_n_test INTEGER,
            all_prev_win_rate_test NUMERIC(14,6),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )$ct$, r.sch, tot);
      EXECUTE ddl;
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.tables x
      WHERE x.table_schema = r.sch AND x.table_name = mon
    ) THEN
      ddl := format($cm$
        CREATE TABLE %I.%I (
            monitor TEXT NOT NULL,
            1d_td_pnl_live NUMERIC(24,8),
            1d_td_ret_pct_live NUMERIC(14,6),
            1d_td_fees_live NUMERIC(24,8),
            1d_td_trades_n_live INTEGER,
            1d_td_win_rate_live NUMERIC(14,6),
            1d_td_pnl_paper NUMERIC(24,8),
            1d_td_ret_pct_paper NUMERIC(14,6),
            1d_td_fees_paper NUMERIC(24,8),
            1d_td_trades_n_paper INTEGER,
            1d_td_win_rate_paper NUMERIC(14,6),
            1d_td_pnl_test NUMERIC(24,8),
            1d_td_ret_pct_test NUMERIC(14,6),
            1d_td_fees_test NUMERIC(24,8),
            1d_td_trades_n_test INTEGER,
            1d_td_win_rate_test NUMERIC(14,6),
            1d_prev_pnl_live NUMERIC(24,8),
            1d_prev_ret_pct_live NUMERIC(14,6),
            1d_prev_fees_live NUMERIC(24,8),
            1d_prev_trades_n_live INTEGER,
            1d_prev_win_rate_live NUMERIC(14,6),
            1d_prev_pnl_paper NUMERIC(24,8),
            1d_prev_ret_pct_paper NUMERIC(14,6),
            1d_prev_fees_paper NUMERIC(24,8),
            1d_prev_trades_n_paper INTEGER,
            1d_prev_win_rate_paper NUMERIC(14,6),
            1d_prev_pnl_test NUMERIC(24,8),
            1d_prev_ret_pct_test NUMERIC(14,6),
            1d_prev_fees_test NUMERIC(24,8),
            1d_prev_trades_n_test INTEGER,
            1d_prev_win_rate_test NUMERIC(14,6),
            1w_td_pnl_live NUMERIC(24,8),
            1w_td_ret_pct_live NUMERIC(14,6),
            1w_td_fees_live NUMERIC(24,8),
            1w_td_trades_n_live INTEGER,
            1w_td_win_rate_live NUMERIC(14,6),
            1w_td_pnl_paper NUMERIC(24,8),
            1w_td_ret_pct_paper NUMERIC(14,6),
            1w_td_fees_paper NUMERIC(24,8),
            1w_td_trades_n_paper INTEGER,
            1w_td_win_rate_paper NUMERIC(14,6),
            1w_td_pnl_test NUMERIC(24,8),
            1w_td_ret_pct_test NUMERIC(14,6),
            1w_td_fees_test NUMERIC(24,8),
            1w_td_trades_n_test INTEGER,
            1w_td_win_rate_test NUMERIC(14,6),
            1w_prev_pnl_live NUMERIC(24,8),
            1w_prev_ret_pct_live NUMERIC(14,6),
            1w_prev_fees_live NUMERIC(24,8),
            1w_prev_trades_n_live INTEGER,
            1w_prev_win_rate_live NUMERIC(14,6),
            1w_prev_pnl_paper NUMERIC(24,8),
            1w_prev_ret_pct_paper NUMERIC(14,6),
            1w_prev_fees_paper NUMERIC(24,8),
            1w_prev_trades_n_paper INTEGER,
            1w_prev_win_rate_paper NUMERIC(14,6),
            1w_prev_pnl_test NUMERIC(24,8),
            1w_prev_ret_pct_test NUMERIC(14,6),
            1w_prev_fees_test NUMERIC(24,8),
            1w_prev_trades_n_test INTEGER,
            1w_prev_win_rate_test NUMERIC(14,6),
            1m_td_pnl_live NUMERIC(24,8),
            1m_td_ret_pct_live NUMERIC(14,6),
            1m_td_fees_live NUMERIC(24,8),
            1m_td_trades_n_live INTEGER,
            1m_td_win_rate_live NUMERIC(14,6),
            1m_td_pnl_paper NUMERIC(24,8),
            1m_td_ret_pct_paper NUMERIC(14,6),
            1m_td_fees_paper NUMERIC(24,8),
            1m_td_trades_n_paper INTEGER,
            1m_td_win_rate_paper NUMERIC(14,6),
            1m_td_pnl_test NUMERIC(24,8),
            1m_td_ret_pct_test NUMERIC(14,6),
            1m_td_fees_test NUMERIC(24,8),
            1m_td_trades_n_test INTEGER,
            1m_td_win_rate_test NUMERIC(14,6),
            1m_prev_pnl_live NUMERIC(24,8),
            1m_prev_ret_pct_live NUMERIC(14,6),
            1m_prev_fees_live NUMERIC(24,8),
            1m_prev_trades_n_live INTEGER,
            1m_prev_win_rate_live NUMERIC(14,6),
            1m_prev_pnl_paper NUMERIC(24,8),
            1m_prev_ret_pct_paper NUMERIC(14,6),
            1m_prev_fees_paper NUMERIC(24,8),
            1m_prev_trades_n_paper INTEGER,
            1m_prev_win_rate_paper NUMERIC(14,6),
            1m_prev_pnl_test NUMERIC(24,8),
            1m_prev_ret_pct_test NUMERIC(14,6),
            1m_prev_fees_test NUMERIC(24,8),
            1m_prev_trades_n_test INTEGER,
            1m_prev_win_rate_test NUMERIC(14,6),
            1y_td_pnl_live NUMERIC(24,8),
            1y_td_ret_pct_live NUMERIC(14,6),
            1y_td_fees_live NUMERIC(24,8),
            1y_td_trades_n_live INTEGER,
            1y_td_win_rate_live NUMERIC(14,6),
            1y_td_pnl_paper NUMERIC(24,8),
            1y_td_ret_pct_paper NUMERIC(14,6),
            1y_td_fees_paper NUMERIC(24,8),
            1y_td_trades_n_paper INTEGER,
            1y_td_win_rate_paper NUMERIC(14,6),
            1y_td_pnl_test NUMERIC(24,8),
            1y_td_ret_pct_test NUMERIC(14,6),
            1y_td_fees_test NUMERIC(24,8),
            1y_td_trades_n_test INTEGER,
            1y_td_win_rate_test NUMERIC(14,6),
            1y_prev_pnl_live NUMERIC(24,8),
            1y_prev_ret_pct_live NUMERIC(14,6),
            1y_prev_fees_live NUMERIC(24,8),
            1y_prev_trades_n_live INTEGER,
            1y_prev_win_rate_live NUMERIC(14,6),
            1y_prev_pnl_paper NUMERIC(24,8),
            1y_prev_ret_pct_paper NUMERIC(14,6),
            1y_prev_fees_paper NUMERIC(24,8),
            1y_prev_trades_n_paper INTEGER,
            1y_prev_win_rate_paper NUMERIC(14,6),
            1y_prev_pnl_test NUMERIC(24,8),
            1y_prev_ret_pct_test NUMERIC(14,6),
            1y_prev_fees_test NUMERIC(24,8),
            1y_prev_trades_n_test INTEGER,
            1y_prev_win_rate_test NUMERIC(14,6),
            all_td_pnl_live NUMERIC(24,8),
            all_td_ret_pct_live NUMERIC(14,6),
            all_td_fees_live NUMERIC(24,8),
            all_td_trades_n_live INTEGER,
            all_td_win_rate_live NUMERIC(14,6),
            all_td_pnl_paper NUMERIC(24,8),
            all_td_ret_pct_paper NUMERIC(14,6),
            all_td_fees_paper NUMERIC(24,8),
            all_td_trades_n_paper INTEGER,
            all_td_win_rate_paper NUMERIC(14,6),
            all_td_pnl_test NUMERIC(24,8),
            all_td_ret_pct_test NUMERIC(14,6),
            all_td_fees_test NUMERIC(24,8),
            all_td_trades_n_test INTEGER,
            all_td_win_rate_test NUMERIC(14,6),
            all_prev_pnl_live NUMERIC(24,8),
            all_prev_ret_pct_live NUMERIC(14,6),
            all_prev_fees_live NUMERIC(24,8),
            all_prev_trades_n_live INTEGER,
            all_prev_win_rate_live NUMERIC(14,6),
            all_prev_pnl_paper NUMERIC(24,8),
            all_prev_ret_pct_paper NUMERIC(14,6),
            all_prev_fees_paper NUMERIC(24,8),
            all_prev_trades_n_paper INTEGER,
            all_prev_win_rate_paper NUMERIC(14,6),
            all_prev_pnl_test NUMERIC(24,8),
            all_prev_ret_pct_test NUMERIC(14,6),
            all_prev_fees_test NUMERIC(24,8),
            all_prev_trades_n_test INTEGER,
            all_prev_win_rate_test NUMERIC(14,6),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (monitor)
        )$cm$, r.sch, mon);
      EXECUTE ddl;
    END IF;
  END LOOP;

  FOR r IN
    SELECT c.table_name AS tname
    FROM information_schema.tables c
    WHERE c.table_type = 'BASE TABLE'
      AND c.table_schema = 'users'
      AND c.table_name ~ '^trades_[0-9]{4}$'
  LOOP
    slot := substring(r.tname from 'trades_([0-9]{4})$');
    tot := 'performance_total_' || slot;
    mon := 'performance_monitors_' || slot;
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.tables x
      WHERE x.table_schema = 'users' AND x.table_name = tot
    ) THEN
      ddl := format($ct$
        CREATE TABLE %I.%I (
            user_id INTEGER PRIMARY KEY DEFAULT 1 CHECK (user_id = 1),
            1d_td_pnl_live NUMERIC(24,8),
            1d_td_ret_pct_live NUMERIC(14,6),
            1d_td_fees_live NUMERIC(24,8),
            1d_td_trades_n_live INTEGER,
            1d_td_win_rate_live NUMERIC(14,6),
            1d_td_pnl_paper NUMERIC(24,8),
            1d_td_ret_pct_paper NUMERIC(14,6),
            1d_td_fees_paper NUMERIC(24,8),
            1d_td_trades_n_paper INTEGER,
            1d_td_win_rate_paper NUMERIC(14,6),
            1d_td_pnl_test NUMERIC(24,8),
            1d_td_ret_pct_test NUMERIC(14,6),
            1d_td_fees_test NUMERIC(24,8),
            1d_td_trades_n_test INTEGER,
            1d_td_win_rate_test NUMERIC(14,6),
            1d_prev_pnl_live NUMERIC(24,8),
            1d_prev_ret_pct_live NUMERIC(14,6),
            1d_prev_fees_live NUMERIC(24,8),
            1d_prev_trades_n_live INTEGER,
            1d_prev_win_rate_live NUMERIC(14,6),
            1d_prev_pnl_paper NUMERIC(24,8),
            1d_prev_ret_pct_paper NUMERIC(14,6),
            1d_prev_fees_paper NUMERIC(24,8),
            1d_prev_trades_n_paper INTEGER,
            1d_prev_win_rate_paper NUMERIC(14,6),
            1d_prev_pnl_test NUMERIC(24,8),
            1d_prev_ret_pct_test NUMERIC(14,6),
            1d_prev_fees_test NUMERIC(24,8),
            1d_prev_trades_n_test INTEGER,
            1d_prev_win_rate_test NUMERIC(14,6),
            1w_td_pnl_live NUMERIC(24,8),
            1w_td_ret_pct_live NUMERIC(14,6),
            1w_td_fees_live NUMERIC(24,8),
            1w_td_trades_n_live INTEGER,
            1w_td_win_rate_live NUMERIC(14,6),
            1w_td_pnl_paper NUMERIC(24,8),
            1w_td_ret_pct_paper NUMERIC(14,6),
            1w_td_fees_paper NUMERIC(24,8),
            1w_td_trades_n_paper INTEGER,
            1w_td_win_rate_paper NUMERIC(14,6),
            1w_td_pnl_test NUMERIC(24,8),
            1w_td_ret_pct_test NUMERIC(14,6),
            1w_td_fees_test NUMERIC(24,8),
            1w_td_trades_n_test INTEGER,
            1w_td_win_rate_test NUMERIC(14,6),
            1w_prev_pnl_live NUMERIC(24,8),
            1w_prev_ret_pct_live NUMERIC(14,6),
            1w_prev_fees_live NUMERIC(24,8),
            1w_prev_trades_n_live INTEGER,
            1w_prev_win_rate_live NUMERIC(14,6),
            1w_prev_pnl_paper NUMERIC(24,8),
            1w_prev_ret_pct_paper NUMERIC(14,6),
            1w_prev_fees_paper NUMERIC(24,8),
            1w_prev_trades_n_paper INTEGER,
            1w_prev_win_rate_paper NUMERIC(14,6),
            1w_prev_pnl_test NUMERIC(24,8),
            1w_prev_ret_pct_test NUMERIC(14,6),
            1w_prev_fees_test NUMERIC(24,8),
            1w_prev_trades_n_test INTEGER,
            1w_prev_win_rate_test NUMERIC(14,6),
            1m_td_pnl_live NUMERIC(24,8),
            1m_td_ret_pct_live NUMERIC(14,6),
            1m_td_fees_live NUMERIC(24,8),
            1m_td_trades_n_live INTEGER,
            1m_td_win_rate_live NUMERIC(14,6),
            1m_td_pnl_paper NUMERIC(24,8),
            1m_td_ret_pct_paper NUMERIC(14,6),
            1m_td_fees_paper NUMERIC(24,8),
            1m_td_trades_n_paper INTEGER,
            1m_td_win_rate_paper NUMERIC(14,6),
            1m_td_pnl_test NUMERIC(24,8),
            1m_td_ret_pct_test NUMERIC(14,6),
            1m_td_fees_test NUMERIC(24,8),
            1m_td_trades_n_test INTEGER,
            1m_td_win_rate_test NUMERIC(14,6),
            1m_prev_pnl_live NUMERIC(24,8),
            1m_prev_ret_pct_live NUMERIC(14,6),
            1m_prev_fees_live NUMERIC(24,8),
            1m_prev_trades_n_live INTEGER,
            1m_prev_win_rate_live NUMERIC(14,6),
            1m_prev_pnl_paper NUMERIC(24,8),
            1m_prev_ret_pct_paper NUMERIC(14,6),
            1m_prev_fees_paper NUMERIC(24,8),
            1m_prev_trades_n_paper INTEGER,
            1m_prev_win_rate_paper NUMERIC(14,6),
            1m_prev_pnl_test NUMERIC(24,8),
            1m_prev_ret_pct_test NUMERIC(14,6),
            1m_prev_fees_test NUMERIC(24,8),
            1m_prev_trades_n_test INTEGER,
            1m_prev_win_rate_test NUMERIC(14,6),
            1y_td_pnl_live NUMERIC(24,8),
            1y_td_ret_pct_live NUMERIC(14,6),
            1y_td_fees_live NUMERIC(24,8),
            1y_td_trades_n_live INTEGER,
            1y_td_win_rate_live NUMERIC(14,6),
            1y_td_pnl_paper NUMERIC(24,8),
            1y_td_ret_pct_paper NUMERIC(14,6),
            1y_td_fees_paper NUMERIC(24,8),
            1y_td_trades_n_paper INTEGER,
            1y_td_win_rate_paper NUMERIC(14,6),
            1y_td_pnl_test NUMERIC(24,8),
            1y_td_ret_pct_test NUMERIC(14,6),
            1y_td_fees_test NUMERIC(24,8),
            1y_td_trades_n_test INTEGER,
            1y_td_win_rate_test NUMERIC(14,6),
            1y_prev_pnl_live NUMERIC(24,8),
            1y_prev_ret_pct_live NUMERIC(14,6),
            1y_prev_fees_live NUMERIC(24,8),
            1y_prev_trades_n_live INTEGER,
            1y_prev_win_rate_live NUMERIC(14,6),
            1y_prev_pnl_paper NUMERIC(24,8),
            1y_prev_ret_pct_paper NUMERIC(14,6),
            1y_prev_fees_paper NUMERIC(24,8),
            1y_prev_trades_n_paper INTEGER,
            1y_prev_win_rate_paper NUMERIC(14,6),
            1y_prev_pnl_test NUMERIC(24,8),
            1y_prev_ret_pct_test NUMERIC(14,6),
            1y_prev_fees_test NUMERIC(24,8),
            1y_prev_trades_n_test INTEGER,
            1y_prev_win_rate_test NUMERIC(14,6),
            all_td_pnl_live NUMERIC(24,8),
            all_td_ret_pct_live NUMERIC(14,6),
            all_td_fees_live NUMERIC(24,8),
            all_td_trades_n_live INTEGER,
            all_td_win_rate_live NUMERIC(14,6),
            all_td_pnl_paper NUMERIC(24,8),
            all_td_ret_pct_paper NUMERIC(14,6),
            all_td_fees_paper NUMERIC(24,8),
            all_td_trades_n_paper INTEGER,
            all_td_win_rate_paper NUMERIC(14,6),
            all_td_pnl_test NUMERIC(24,8),
            all_td_ret_pct_test NUMERIC(14,6),
            all_td_fees_test NUMERIC(24,8),
            all_td_trades_n_test INTEGER,
            all_td_win_rate_test NUMERIC(14,6),
            all_prev_pnl_live NUMERIC(24,8),
            all_prev_ret_pct_live NUMERIC(14,6),
            all_prev_fees_live NUMERIC(24,8),
            all_prev_trades_n_live INTEGER,
            all_prev_win_rate_live NUMERIC(14,6),
            all_prev_pnl_paper NUMERIC(24,8),
            all_prev_ret_pct_paper NUMERIC(14,6),
            all_prev_fees_paper NUMERIC(24,8),
            all_prev_trades_n_paper INTEGER,
            all_prev_win_rate_paper NUMERIC(14,6),
            all_prev_pnl_test NUMERIC(24,8),
            all_prev_ret_pct_test NUMERIC(14,6),
            all_prev_fees_test NUMERIC(24,8),
            all_prev_trades_n_test INTEGER,
            all_prev_win_rate_test NUMERIC(14,6),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )$ct$, 'users', tot);
      EXECUTE ddl;
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.tables x
      WHERE x.table_schema = 'users' AND x.table_name = mon
    ) THEN
      ddl := format($cm$
        CREATE TABLE %I.%I (
            monitor TEXT NOT NULL,
            1d_td_pnl_live NUMERIC(24,8),
            1d_td_ret_pct_live NUMERIC(14,6),
            1d_td_fees_live NUMERIC(24,8),
            1d_td_trades_n_live INTEGER,
            1d_td_win_rate_live NUMERIC(14,6),
            1d_td_pnl_paper NUMERIC(24,8),
            1d_td_ret_pct_paper NUMERIC(14,6),
            1d_td_fees_paper NUMERIC(24,8),
            1d_td_trades_n_paper INTEGER,
            1d_td_win_rate_paper NUMERIC(14,6),
            1d_td_pnl_test NUMERIC(24,8),
            1d_td_ret_pct_test NUMERIC(14,6),
            1d_td_fees_test NUMERIC(24,8),
            1d_td_trades_n_test INTEGER,
            1d_td_win_rate_test NUMERIC(14,6),
            1d_prev_pnl_live NUMERIC(24,8),
            1d_prev_ret_pct_live NUMERIC(14,6),
            1d_prev_fees_live NUMERIC(24,8),
            1d_prev_trades_n_live INTEGER,
            1d_prev_win_rate_live NUMERIC(14,6),
            1d_prev_pnl_paper NUMERIC(24,8),
            1d_prev_ret_pct_paper NUMERIC(14,6),
            1d_prev_fees_paper NUMERIC(24,8),
            1d_prev_trades_n_paper INTEGER,
            1d_prev_win_rate_paper NUMERIC(14,6),
            1d_prev_pnl_test NUMERIC(24,8),
            1d_prev_ret_pct_test NUMERIC(14,6),
            1d_prev_fees_test NUMERIC(24,8),
            1d_prev_trades_n_test INTEGER,
            1d_prev_win_rate_test NUMERIC(14,6),
            1w_td_pnl_live NUMERIC(24,8),
            1w_td_ret_pct_live NUMERIC(14,6),
            1w_td_fees_live NUMERIC(24,8),
            1w_td_trades_n_live INTEGER,
            1w_td_win_rate_live NUMERIC(14,6),
            1w_td_pnl_paper NUMERIC(24,8),
            1w_td_ret_pct_paper NUMERIC(14,6),
            1w_td_fees_paper NUMERIC(24,8),
            1w_td_trades_n_paper INTEGER,
            1w_td_win_rate_paper NUMERIC(14,6),
            1w_td_pnl_test NUMERIC(24,8),
            1w_td_ret_pct_test NUMERIC(14,6),
            1w_td_fees_test NUMERIC(24,8),
            1w_td_trades_n_test INTEGER,
            1w_td_win_rate_test NUMERIC(14,6),
            1w_prev_pnl_live NUMERIC(24,8),
            1w_prev_ret_pct_live NUMERIC(14,6),
            1w_prev_fees_live NUMERIC(24,8),
            1w_prev_trades_n_live INTEGER,
            1w_prev_win_rate_live NUMERIC(14,6),
            1w_prev_pnl_paper NUMERIC(24,8),
            1w_prev_ret_pct_paper NUMERIC(14,6),
            1w_prev_fees_paper NUMERIC(24,8),
            1w_prev_trades_n_paper INTEGER,
            1w_prev_win_rate_paper NUMERIC(14,6),
            1w_prev_pnl_test NUMERIC(24,8),
            1w_prev_ret_pct_test NUMERIC(14,6),
            1w_prev_fees_test NUMERIC(24,8),
            1w_prev_trades_n_test INTEGER,
            1w_prev_win_rate_test NUMERIC(14,6),
            1m_td_pnl_live NUMERIC(24,8),
            1m_td_ret_pct_live NUMERIC(14,6),
            1m_td_fees_live NUMERIC(24,8),
            1m_td_trades_n_live INTEGER,
            1m_td_win_rate_live NUMERIC(14,6),
            1m_td_pnl_paper NUMERIC(24,8),
            1m_td_ret_pct_paper NUMERIC(14,6),
            1m_td_fees_paper NUMERIC(24,8),
            1m_td_trades_n_paper INTEGER,
            1m_td_win_rate_paper NUMERIC(14,6),
            1m_td_pnl_test NUMERIC(24,8),
            1m_td_ret_pct_test NUMERIC(14,6),
            1m_td_fees_test NUMERIC(24,8),
            1m_td_trades_n_test INTEGER,
            1m_td_win_rate_test NUMERIC(14,6),
            1m_prev_pnl_live NUMERIC(24,8),
            1m_prev_ret_pct_live NUMERIC(14,6),
            1m_prev_fees_live NUMERIC(24,8),
            1m_prev_trades_n_live INTEGER,
            1m_prev_win_rate_live NUMERIC(14,6),
            1m_prev_pnl_paper NUMERIC(24,8),
            1m_prev_ret_pct_paper NUMERIC(14,6),
            1m_prev_fees_paper NUMERIC(24,8),
            1m_prev_trades_n_paper INTEGER,
            1m_prev_win_rate_paper NUMERIC(14,6),
            1m_prev_pnl_test NUMERIC(24,8),
            1m_prev_ret_pct_test NUMERIC(14,6),
            1m_prev_fees_test NUMERIC(24,8),
            1m_prev_trades_n_test INTEGER,
            1m_prev_win_rate_test NUMERIC(14,6),
            1y_td_pnl_live NUMERIC(24,8),
            1y_td_ret_pct_live NUMERIC(14,6),
            1y_td_fees_live NUMERIC(24,8),
            1y_td_trades_n_live INTEGER,
            1y_td_win_rate_live NUMERIC(14,6),
            1y_td_pnl_paper NUMERIC(24,8),
            1y_td_ret_pct_paper NUMERIC(14,6),
            1y_td_fees_paper NUMERIC(24,8),
            1y_td_trades_n_paper INTEGER,
            1y_td_win_rate_paper NUMERIC(14,6),
            1y_td_pnl_test NUMERIC(24,8),
            1y_td_ret_pct_test NUMERIC(14,6),
            1y_td_fees_test NUMERIC(24,8),
            1y_td_trades_n_test INTEGER,
            1y_td_win_rate_test NUMERIC(14,6),
            1y_prev_pnl_live NUMERIC(24,8),
            1y_prev_ret_pct_live NUMERIC(14,6),
            1y_prev_fees_live NUMERIC(24,8),
            1y_prev_trades_n_live INTEGER,
            1y_prev_win_rate_live NUMERIC(14,6),
            1y_prev_pnl_paper NUMERIC(24,8),
            1y_prev_ret_pct_paper NUMERIC(14,6),
            1y_prev_fees_paper NUMERIC(24,8),
            1y_prev_trades_n_paper INTEGER,
            1y_prev_win_rate_paper NUMERIC(14,6),
            1y_prev_pnl_test NUMERIC(24,8),
            1y_prev_ret_pct_test NUMERIC(14,6),
            1y_prev_fees_test NUMERIC(24,8),
            1y_prev_trades_n_test INTEGER,
            1y_prev_win_rate_test NUMERIC(14,6),
            all_td_pnl_live NUMERIC(24,8),
            all_td_ret_pct_live NUMERIC(14,6),
            all_td_fees_live NUMERIC(24,8),
            all_td_trades_n_live INTEGER,
            all_td_win_rate_live NUMERIC(14,6),
            all_td_pnl_paper NUMERIC(24,8),
            all_td_ret_pct_paper NUMERIC(14,6),
            all_td_fees_paper NUMERIC(24,8),
            all_td_trades_n_paper INTEGER,
            all_td_win_rate_paper NUMERIC(14,6),
            all_td_pnl_test NUMERIC(24,8),
            all_td_ret_pct_test NUMERIC(14,6),
            all_td_fees_test NUMERIC(24,8),
            all_td_trades_n_test INTEGER,
            all_td_win_rate_test NUMERIC(14,6),
            all_prev_pnl_live NUMERIC(24,8),
            all_prev_ret_pct_live NUMERIC(14,6),
            all_prev_fees_live NUMERIC(24,8),
            all_prev_trades_n_live INTEGER,
            all_prev_win_rate_live NUMERIC(14,6),
            all_prev_pnl_paper NUMERIC(24,8),
            all_prev_ret_pct_paper NUMERIC(14,6),
            all_prev_fees_paper NUMERIC(24,8),
            all_prev_trades_n_paper INTEGER,
            all_prev_win_rate_paper NUMERIC(14,6),
            all_prev_pnl_test NUMERIC(24,8),
            all_prev_ret_pct_test NUMERIC(14,6),
            all_prev_fees_test NUMERIC(24,8),
            all_prev_trades_n_test INTEGER,
            all_prev_win_rate_test NUMERIC(14,6),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (monitor)
        )$cm$, 'users', mon);
      EXECUTE ddl;
    END IF;
  END LOOP;
END;
$$;

DO $$
DECLARE
  r RECORD;
  tname text;
BEGIN
  FOR r IN
    SELECT c.table_schema, c.table_name
    FROM information_schema.tables c
    WHERE c.table_type = 'BASE TABLE'
      AND c.table_schema ~ '^users_[0-9]{4}$'
      AND (c.table_name ~ '^performance_total_[0-9]{4}$' OR c.table_name ~ '^performance_monitors_[0-9]{4}$')
      AND substring(c.table_schema from '([0-9]{4})$') = substring(c.table_name from '([0-9]{4})$')
  LOOP
    tname := r.table_name || '_rec_io_db_notify';
    EXECUTE format(
      'DROP TRIGGER IF EXISTS %I ON %I.%I',
      tname, r.table_schema, r.table_name
    );
    EXECUTE format(
      'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON %I.%I FOR EACH ROW EXECUTE PROCEDURE public.rec_io_db_notify()',
      tname, r.table_schema, r.table_name
    );
  END LOOP;
END;
$$;

DO $$
DECLARE
  r RECORD;
  tname text;
BEGIN
  FOR r IN
    SELECT c.table_name
    FROM information_schema.tables c
    WHERE c.table_type = 'BASE TABLE'
      AND c.table_schema = 'users'
      AND (c.table_name ~ '^performance_total_[0-9]{4}$' OR c.table_name ~ '^performance_monitors_[0-9]{4}$')
  LOOP
    tname := r.table_name || '_rec_io_db_notify';
    EXECUTE format(
      'DROP TRIGGER IF EXISTS %I ON users.%I',
      tname, r.table_name
    );
    EXECUTE format(
      'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON users.%I FOR EACH ROW EXECUTE PROCEDURE public.rec_io_db_notify()',
      tname, r.table_name
    );
  END LOOP;
END;
$$;
