ALTER TABLE live_data.market_kalshi_15m
  ADD COLUMN IF NOT EXISTS yes_bid INTEGER,
  ADD COLUMN IF NOT EXISTS yes_ask INTEGER,
  ADD COLUMN IF NOT EXISTS no_bid INTEGER,
  ADD COLUMN IF NOT EXISTS no_ask INTEGER,
  ADD COLUMN IF NOT EXISTS last_price INTEGER,
  ADD COLUMN IF NOT EXISTS volume_24h_fp INTEGER,
  ADD COLUMN IF NOT EXISTS liquidity INTEGER;
